### ISSUE TITLE
the first run-through to get subreddit statuses is *so* cpu intensive

### ISSUE THREAD

**Issue by username-is-required** [username-is-required/reddark#60]
but then all the runs of updateStatus after are really fucking quick and use hardly any cpu at all??

idk whats up

**Comment by username-is-required** [comment]
i remember that this issue first started after deploying 8e194b6, so my guess would be that the cpu-intensitivity could come from the app suddenly needing to interact with individual sockets rather than just emitting everything to everyone. maybe also with having to listen for `client-info` messages? idk.

but then how come the extremely high cpu usage **only** lasts for the duration of the *first* call to `updateStatus()`, then drops down from ~95% to around 40% from then on (with all future calls to `updateStatus()` being processed much more quickly as well)? maybe there’s something in the way the **first** request is processed that exacerbates the problem? i’m not sure. 

all in all i have absolutely no idea.

**Comment by username-is-required** [comment]
![IMG_9334](https://github.com/username-is-required/reddark/assets/136007111/1580cdbf-cb9d-4c91-b116-0dda347c52a8)

**Comment by username-is-required** [comment]
okay so i spun up a separate instance on digitalocean (from f9a0428) to see if the high CPU would be replicated, and it wasn’t. as far as i can think, the only/main difference between this separate instance and when i pushed f9a0428 to the main instance was the number of connections. this makes me think that it’s *something* to do with the number of connections that causes cpu usage to massively increase during the first `updateStatus` call.

but this still doesn’t explain why it’s **only** during the **first** `updateStatus` call that cpu usage is so heavy.

(i shut it down before the first check was complete - because reddit was heavily rate limiting - but if that had been a deployment to the main app the cpu would have already spiked by the time i shut it down.)

![IMG_9336](https://github.com/username-is-required/reddark/assets/136007111/ed162a8c-ada7-4268-9355-440bfb0536de)

**Comment by username-is-required** [comment]
okay well i unintentionally pushed a change that disconnected nearly (but not quite) everyone, and the change i pushed *after that* had a much faster first run of `updateStatus`. so it’s definitely something to do with the number of connections. just still no clue why it only causes a problem on the *first run* of `updateStatus`.

**Comment by lokzz** [comment]
could be related but
on first few run/checks, i get a lot of socket timeouts
but after about 30 checks, they just stop

**Comment by username-is-required** [comment]
@lokzz that’s interesting - do you see any obvious changes in metrics that coincide with the timeouts? e.g. spikes in cpu usage, memory, etc

**Comment by username-is-required** [comment]
pretty sure this was unintentionally solved by #70 virtually eliminating my redeployment downtime. too bad i never figured out what was causing it lol

**Comment by username-is-required** [comment]
yep! no idea what the underlying cause behind the *original* problem was, but with a hundredfold reduction in the number of api calls needed per cycle, this is no longer an issue so i’m closing it. (if it decides to make a return i’ll reopen it)
