### ISSUE TITLE
feature if possible: list what subreddits are going dark for 2 days, a week, indefinitely, etc.

### ISSUE THREAD

**Issue by sI1vre** [username-is-required/reddark#65]
definitely harder because its all private and stuff, but theres more cases than i want to admit where i have no idea how long a sub is going down. an infographic *somewhere*, even if incomplete, would be amazing

**Comment by username-is-required** [comment]
i agree that that could be a nice thing to have, however i’m not sure how feasible it would be to implement unfortunately, as i’m not aware of any single source of information for how long a subreddit is closing for. this would mean that i’d have to go through single subreddit and individually research how long they’ll be closed for. (like you mention, it’s also harder now the subs are private, as we can’t see the posts where they say how long they’re going down for - and i don’t think mods would appreciate collective hundreds of modmails from me asking the question 🤣) 

i’m not sure if any other websites/apps have collated this information, but if i happen to notice one, i’ll try and remember to link it back here!

**Comment by username-is-required** [comment]
@sI1vre just to say that i noticed another website that has graphs you might be interested in (although i don’t believe they give information on when currently closed subs will reopen, just how long they’ve been closed for): https://blackout.photon-reddit.com (disclaimer that i obviously don’t operate this site myself and so aren’t responsible for its contents, etc.).

bear in mind that as per the notes at the top of that page, it’s not been tracking **all** the subs involved in the blackout:

> This list includes the **top 1000 SFW and 500 NSFW most popular** subreddits.

**Comment by username-is-required** [comment]
closing this now as i don’t plan to implement the feature. plus at the moment with everything up in the air with what the admins have been doing, i feel such a feature might have a limited use (as even if a sub has said it’ll go private for X amount of time, the modteam might well decide to open up again earlier than planned following thinly veiled admin threats)
